version: "3.8"
services:
  native-service:
    depends_on:
      - native-postgres
    image: "native"
    container_name: "native-service"
    ports:
      - 8080:8080
      - 8000:8000
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_R2DBC_URL=r2dbc:postgresql://native-postgres:5432/native_db
      - SPRING_FLYWAY_URL=jdbc:postgresql://native-postgres:5432/native_db
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000

  native-postgres:
    image: "postgres:14.4"
    container_name: "native-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=native_db